"""phase2 persistent campus schema
Revision ID: 0001
Revises:
"""

import geoalchemy2
import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("icon", sa.String(length=80), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenities")),
        sa.UniqueConstraint("slug", name=op.f("uq_amenities_slug")),
    )
    op.create_table(
        "campuses",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("university_name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_campuses_latitude")),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name=op.f("ck_campuses_longitude")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campuses")),
        sa.UniqueConstraint("slug", name=op.f("uq_campuses_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("points", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reliability_score", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("points >= 0", name=op.f("ck_users_points")),
        sa.CheckConstraint("reliability_score BETWEEN 0 AND 1", name=op.f("ck_users_reliability")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "buildings",
        sa.Column("campus_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_buildings_latitude")),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name=op.f("ck_buildings_longitude")),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
            name=op.f("fk_buildings_campus_id_campuses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
        sa.UniqueConstraint("campus_id", "name", name=op.f("uq_buildings_campus_id")),
    )
    op.create_index(op.f("ix_buildings_campus_id"), "buildings", ["campus_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "noise_preference",
            sa.Enum(
                "quiet",
                "moderate",
                "social",
                "any",
                name="noisepreference",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "study_style",
            sa.Enum(
                "solo",
                "group",
                "both",
                name="studystyle",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("max_walking_minutes", sa.Integer(), nullable=False),
        sa.Column("study_duration_hours", sa.Float(), server_default="1", nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_walking_minutes > 0 AND max_walking_minutes <= 240",
            name=op.f("ck_user_preferences_walking_minutes"),
        ),
        sa.CheckConstraint(
            "study_duration_hours > 0 AND study_duration_hours <= 12",
            name=op.f("ck_user_preferences_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_preferences_user_id")),
    )
    op.create_table(
        "preference_amenities",
        sa.Column("preference_id", sa.String(length=64), nullable=False),
        sa.Column("amenity_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name=op.f("fk_preference_amenities_amenity_id_amenities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["user_preferences.id"],
            name=op.f("fk_preference_amenities_preference_id_user_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "preference_id", "amenity_id", name=op.f("pk_preference_amenities")
        ),
    )
    op.create_table(
        "study_locations",
        sa.Column("building_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("floor", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geo_point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            sa.Computed(
                "ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "noise_level",
            sa.Enum(
                "quiet",
                "moderate",
                "social",
                name="noiselevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity >= 0", name=op.f("ck_study_locations_capacity")),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_study_locations_latitude")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_study_locations_longitude")
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_study_locations_building_id_buildings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_locations")),
        sa.UniqueConstraint("building_id", "slug", name=op.f("uq_study_locations_building_id")),
    )
    op.create_index(
        op.f("ix_study_locations_building_id"), "study_locations", ["building_id"], unique=False
    )
    op.create_index(
        "ix_study_locations_geo_point",
        "study_locations",
        ["geo_point"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_favorites_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
        sa.UniqueConstraint("user_id", "location_id", name=op.f("uq_favorites_user_id")),
    )
    op.create_index(op.f("ix_favorites_location_id"), "favorites", ["location_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.create_table(
        "location_amenities",
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("amenity_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name=op.f("fk_location_amenities_amenity_id_amenities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_location_amenities_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("location_id", "amenity_id", name=op.f("pk_location_amenities")),
    )
    op.create_table(
        "occupancy_estimates",
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("occupancy_percent", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="confidencelevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "seed",
                "manual",
                "crowd_report",
                "model",
                "derived",
                "sensor",
                name="occupancysource",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "occupancy_percent BETWEEN 0 AND 100", name=op.f("ck_occupancy_estimates_percent")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_occupancy_estimates_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupancy_estimates")),
    )
    op.create_index(
        "ix_estimates_location_time",
        "occupancy_estimates",
        ["location_id", "estimated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_occupancy_estimates_estimated_at"),
        "occupancy_estimates",
        ["estimated_at"],
        unique=False,
    )
    op.create_table(
        "occupancy_observations",
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("occupancy_percent", sa.Integer(), nullable=False),
        sa.Column("occupied_seats", sa.Integer(), nullable=True),
        sa.Column("total_seats", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "seed",
                "manual",
                "crowd_report",
                "model",
                "derived",
                "sensor",
                name="occupancysource",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "occupancy_percent BETWEEN 0 AND 100", name=op.f("ck_occupancy_observations_percent")
        ),
        sa.CheckConstraint(
            "occupied_seats <= total_seats", name=op.f("ck_occupancy_observations_seat_counts")
        ),
        sa.CheckConstraint(
            "occupied_seats >= 0", name=op.f("ck_occupancy_observations_occupied_seats")
        ),
        sa.CheckConstraint("total_seats >= 0", name=op.f("ck_occupancy_observations_total_seats")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_occupancy_observations_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupancy_observations")),
    )
    op.create_index(
        "ix_observations_location_time",
        "occupancy_observations",
        ["location_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "occupancy_predictions",
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("target_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_occupancy", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="confidencelevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "seed",
                "manual",
                "crowd_report",
                "model",
                "derived",
                "sensor",
                name="occupancysource",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "predicted_occupancy BETWEEN 0 AND 100", name=op.f("ck_occupancy_predictions_percent")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_occupancy_predictions_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupancy_predictions")),
        sa.UniqueConstraint(
            "location_id",
            "target_time",
            "model_version",
            name=op.f("uq_occupancy_predictions_location_id"),
        ),
    )
    op.create_index(
        op.f("ix_occupancy_predictions_target_time"),
        "occupancy_predictions",
        ["target_time"],
        unique=False,
    )
    op.create_index(
        "ix_predictions_location_time",
        "occupancy_predictions",
        ["location_id", "target_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_location_time", table_name="occupancy_predictions")
    op.drop_index(op.f("ix_occupancy_predictions_target_time"), table_name="occupancy_predictions")
    op.drop_table("occupancy_predictions")
    op.drop_index("ix_observations_location_time", table_name="occupancy_observations")
    op.drop_table("occupancy_observations")
    op.drop_index(op.f("ix_occupancy_estimates_estimated_at"), table_name="occupancy_estimates")
    op.drop_index("ix_estimates_location_time", table_name="occupancy_estimates")
    op.drop_table("occupancy_estimates")
    op.drop_table("location_amenities")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_location_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(
        "ix_study_locations_geo_point", table_name="study_locations", postgresql_using="gist"
    )
    op.drop_index(op.f("ix_study_locations_building_id"), table_name="study_locations")
    op.drop_table("study_locations")
    op.drop_table("preference_amenities")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_buildings_campus_id"), table_name="buildings")
    op.drop_table("buildings")
    op.drop_table("users")
    op.drop_table("campuses")
    op.drop_table("amenities")
    # ### end Alembic commands ###
