"""phase5 occupancy contributions
Revision ID: 25630308138d
Revises: 0002
"""

import sqlalchemy as sa

from alembic import op

revision = "25630308138d"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkins",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "completed",
                "expired",
                name="checkinstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_distance_meters", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checked_out_at IS NULL OR checked_out_at >= checked_in_at",
            name=op.f("ck_checkins_chronology"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_checkins_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_checkins_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkins")),
    )
    op.create_index(
        "ix_checkins_location_status_expiry",
        "checkins",
        ["location_id", "status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_checkins_one_active_user",
        "checkins",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(op.f("ix_checkins_user_id"), "checkins", ["user_id"], unique=False)
    op.create_table(
        "crowd_reports",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column(
            "crowd_level",
            sa.Enum(
                "lots_of_seats",
                "moderate",
                "busy",
                "nearly_full",
                name="crowdlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("normalized_value", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_verified", sa.Boolean(), nullable=False),
        sa.Column("user_reliability_at_submission", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "normalized_value BETWEEN 0 AND 100", name=op.f("ck_crowd_reports_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_crowd_reports_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_crowd_reports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crowd_reports")),
    )
    op.create_index(
        "ix_reports_location_time", "crowd_reports", ["location_id", "submitted_at"], unique=False
    )
    op.create_index(
        "ix_reports_user_location_time",
        "crowd_reports",
        ["user_id", "location_id", "submitted_at"],
        unique=False,
    )
    op.create_table(
        "occupancy_validations",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("estimate_id", sa.String(length=64), nullable=False),
        sa.Column(
            "validation_type",
            sa.Enum(
                "accurate",
                "more_crowded",
                "less_crowded",
                name="validationtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["occupancy_estimates.id"],
            name=op.f("fk_occupancy_validations_estimate_id_occupancy_estimates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["study_locations.id"],
            name=op.f("fk_occupancy_validations_location_id_study_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_occupancy_validations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupancy_validations")),
        sa.UniqueConstraint(
            "user_id", "estimate_id", name=op.f("uq_occupancy_validations_user_id")
        ),
    )
    op.create_index(
        "ix_validations_location_time",
        "occupancy_validations",
        ["location_id", "submitted_at"],
        unique=False,
    )
    op.add_column(
        "occupancy_estimates",
        sa.Column("confidence_score", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "occupancy_estimates",
        sa.Column("signal_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.alter_column(
        "occupancy_estimates", "occupancy_percent", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(op.f("ck_occupancy_estimates_percent"), "occupancy_estimates", type_="check")
    op.create_check_constraint(
        op.f("ck_occupancy_estimates_percent"),
        "occupancy_estimates",
        "occupancy_percent IS NULL OR occupancy_percent BETWEEN 0 AND 100",
    )
    op.create_check_constraint(
        op.f("ck_occupancy_estimates_confidence_score"),
        "occupancy_estimates",
        "confidence_score BETWEEN 0 AND 1",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM occupancy_estimates WHERE occupancy_percent IS NULL")
    op.drop_constraint(
        op.f("ck_occupancy_estimates_confidence_score"), "occupancy_estimates", type_="check"
    )
    op.drop_constraint(op.f("ck_occupancy_estimates_percent"), "occupancy_estimates", type_="check")
    op.create_check_constraint(
        op.f("ck_occupancy_estimates_percent"),
        "occupancy_estimates",
        "occupancy_percent BETWEEN 0 AND 100",
    )
    op.alter_column(
        "occupancy_estimates", "occupancy_percent", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("occupancy_estimates", "signal_count")
    op.drop_column("occupancy_estimates", "confidence_score")
    op.drop_index("ix_validations_location_time", table_name="occupancy_validations")
    op.drop_table("occupancy_validations")
    op.drop_index("ix_reports_user_location_time", table_name="crowd_reports")
    op.drop_index("ix_reports_location_time", table_name="crowd_reports")
    op.drop_table("crowd_reports")
    op.drop_index(op.f("ix_checkins_user_id"), table_name="checkins")
    op.drop_index(
        "ix_checkins_one_active_user",
        table_name="checkins",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_checkins_location_status_expiry", table_name="checkins")
    op.drop_table("checkins")
    # ### end Alembic commands ###
